version: '3.8'

# Development overrides
services:
  web:
    environment:
      - DEBUG=true
      - NODE_ENV=development
    volumes:
      - .:/app:cached
      - /app/node_modules
    command: python3 -m http.server 8000

  api-proxy:
    environment:
      - DEBUG=true
      - NODE_ENV=development
    volumes:
      - ./server:/app:cached
      - /app/node_modules
    command: npm run dev

  # Development database for testing
  test-db:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    networks:
      - quiz-network
    volumes:
      - test-db-data:/data

volumes:
  test-db-data: